// web/src/lib/components/base/header.svelte
<header class="">
  <div class="container flex items-center justify-between pt-6 pb-4">
    <a href="/" class="text-2xl uppercase font-medium font-poetry">Rime</a>

    <nav>
      <ul class="flex items-center gap-4">
        <li><a href="/auth/login">Login</a></li>
        <li><a href="/auth/register">Register</a></li>
      </ul>
    </nav>
  </div>
</header>

<style>
  
</style>

// web/components/app/Header.vue
<script setup lang="ts"></script>

<template>
  <header class="pt-7 pb-5">
    <div class="container flex items-center justify-between">
      <NuxtLink to="/">
        <AppLogo />
      </NuxtLink>

      <div class="flex gap-4 items-center">
        <AppNavigation />
        <AppThemeToggle />
      </div>
    </div>
  </header>
</template>
